(function(){var f=true,g=null,h=false,aa=encodeURIComponent,i=window,ba=Object,k=navigator,ca=undefined,m=parseInt,n=document,da=decodeURIComponent,o=Math;function ea(a,b){return a.width=b}function fa(a,b){return a.toString=b}function ga(a,b){return a.height=b}
var ha="appendChild",q="push",ia="valueOf",ja="width",ka="round",la="slice",r="replace",ma="floor",na="cookie",oa="charAt",pa="_height_",s="indexOf",u="write",qa="domain",ra="match",sa="opera",v="_html_",ua="createElement",w="getParameter",va="addEventListener",wa="referrer",xa="attachEvent",ya="name",za="contentWindow",Aa="getTime",Ba="getElementsByTagName",x="toString",y="length",Ca="propertyIsEnumerable",Da="plugins",z="prototype",Ea="setTimeout",A="document",B="split",C="userAgent",D="screen",
E="style",Fa="body",Ga="_width_",F="call",G="random",Ha="_is_afc_",H="substring",Ia="navigator",Ja="parentNode",Ka="height",I="join",La="toLowerCase",J=this,Ma=function(a,b,c){a=a[B](".");c=c||J;!(a[0]in c)&&c.execScript&&c.execScript("var "+a[0]);for(var d;a[y]&&(d=a.shift());)if(!a[y]&&b!==ca)c[d]=b;else c=c[d]?c[d]:(c[d]={})},Na=function(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array||!(a instanceof ba)&&ba[z][x][F](a)=="[object Array]"||typeof a[y]=="number"&&typeof a.splice!="undefined"&&
typeof a[Ca]!="undefined"&&!a[Ca]("splice"))return"array";if(!(a instanceof ba)&&(ba[z][x][F](a)=="[object Function]"||typeof a[F]!="undefined"&&typeof a[Ca]!="undefined"&&!a[Ca]("call")))return"function"}else return"null";else if(b=="function"&&typeof a[F]=="undefined")return"object";return b};o[ma](o[G]()*2147483648)[x](36);
var Oa=function(a,b){var c=b||J;if(arguments[y]>2){var d=Array[z][la][F](arguments,2);return function(){var e=Array[z][la][F](arguments);Array[z].unshift.apply(e,d);return a.apply(c,e)}}else return function(){return a.apply(c,arguments)}},K=function(a,b,c){Ma(a,b,c)},Pa=function(a,b,c){a[b]=c},Qa=function(a,b){function c(){}c.prototype=b[z];a.Ba=b[z];a.prototype=new c};var Ra=function(a,b){var c=parseFloat(a);return isNaN(c)||c>1||c<0?b:c},Sa=function(a,b){if(a=="true")return f;if(a=="false")return h;return b},Ta=/^([\w-]+\.)*([\w-]{2,})(\:[0-9]+)?$/,Ua=function(a,b){if(!a)return b;var c=a[ra](Ta);return c?c[0]:b};var Va=function(){return Ua("","pagead2.googlesyndication.com")};var Ya=function(a){if(a[s]("&")!=-1)return"document"in J&&a[s]("<")==-1?Wa(a):Xa(a);return a},Wa=function(a){var b=J[A][ua]("a");b.innerHTML=a;b.normalize&&b.normalize();a=b.firstChild.nodeValue;b.innerHTML="";return a},Xa=function(a){return a[r](/&([^;]+);/g,function(b,c){switch(c){case "amp":return"&";case "lt":return"<";case "gt":return">";case "quot":return'"';default:if(c[oa](0)=="#"){var d=Number("0"+c.substr(1));if(!isNaN(d))return String.fromCharCode(d)}return b}})},$a=function(a,b){for(var c=
0,d=String(a)[r](/^[\s\xa0]+|[\s\xa0]+$/g,"")[B]("."),e=String(b)[r](/^[\s\xa0]+|[\s\xa0]+$/g,"")[B]("."),l=o.max(d[y],e[y]),j=0;c==0&&j<l;j++){var p=d[j]||"",t=e[j]||"",ta=RegExp("(\\d*)(\\D*)","g"),T=RegExp("(\\d*)(\\D*)","g");do{var U=ta.exec(p)||["","",""],V=T.exec(t)||["","",""];if(U[0][y]==0&&V[0][y]==0)break;c=U[1][y]==0?0:m(U[1],10);var gb=V[1][y]==0?0:m(V[1],10);c=Za(c,gb)||Za(U[2][y]==0,V[2][y]==0)||Za(U[2],V[2])}while(c==0)}return c},Za=function(a,b){if(a<b)return-1;else if(a>b)return 1;
return 0};var ab=function(a,b){ea(this,a);ga(this,b)};ab[z].floor=function(){ea(this,o[ma](this[ja]));ga(this,o[ma](this[Ka]));return this};ab[z].round=function(){ea(this,o[ka](this[ja]));ga(this,o[ka](this[Ka]));return this};var bb,cb,db,eb,fb,hb,ib,jb,kb,lb=function(){return J[Ia]?J[Ia][C]:g},mb=function(){return J[Ia]},nb=function(){fb=eb=db=cb=bb=h;var a;if(a=lb()){var b=mb();bb=a[s]("Opera")==0;cb=!bb&&a[s]("MSIE")!=-1;eb=(db=!bb&&a[s]("WebKit")!=-1)&&a[s]("Mobile")!=-1;fb=!bb&&!db&&b.product=="Gecko"}};nb();
var ob=bb,pb=cb,qb=fb,rb=db,sb=eb,tb=function(){var a=mb();return a&&a.platform||""},ub=tb(),vb=function(){hb=ub[s]("Mac")!=-1;ib=ub[s]("Win")!=-1;jb=ub[s]("Linux")!=-1;kb=!!mb()&&(mb().appVersion||"")[s]("X11")!=-1};vb();var wb=function(){var a="",b;if(ob&&J[sa]){a=J[sa].version;a=typeof a=="function"?a():a}else{if(qb)b=/rv\:([^\);]+)(\)|;)/;else if(pb)b=/MSIE\s+([^\);]+)(\)|;)/;else if(rb)b=/WebKit\/(\S+)/;if(b)a=(a=b.exec(lb()))?a[1]:""}return a},xb=wb(),yb={};var zb=function(a){var b=a[A];if(rb&&!(yb["500"]||(yb["500"]=$a(xb,"500")>=0))&&!sb){if(typeof a.innerHeight=="undefined")a=i;b=a.innerHeight;var c=a[A].documentElement.scrollHeight;if(a==a.top)if(c<b)b-=15;return new ab(a.innerWidth,b)}a=b.compatMode=="CSS1Compat"&&(!ob||ob&&(yb["9.50"]||(yb["9.50"]=$a(xb,"9.50")>=0)))?b.documentElement:b[Fa];return new ab(a.clientWidth,a.clientHeight)};var Ab=n,L=i,Bb=function(a){var b=g;if((a=a[Ba]("script"))&&a[y]){b=a[a[y]-1];b=b[Ja]}return b};Bb(Ab);var Cb="http://"+Va()+"/pagead/show_ads.js";function M(a){return typeof aa=="function"?aa(a):escape(a)}function Db(a,b,c){var d=n[ua]("script");d.type="text/javascript";if(b)d.onload=b;if(c)d.id=c;d.src=a;var e=n[Ba]("head")[0];if(!e)return h;i[Ea](function(){e[ha](d)},0);return f}function Eb(a,b){if(a[xa]){a[xa]("onload",b);return f}if(a[va]){a[va]("load",b,h);return f}return h}var Fb=function(a){if(!("google_onload_fired"in a)){a.google_onload_fired=h;Eb(a,function(){a.google_onload_fired=f})}};
function Gb(a,b){a.google_image_requests||(a.google_image_requests=[]);var c=new Image;c.src=b;a.google_image_requests[q](c)}function Hb(a){if(a in Ib)return Ib[a];return Ib[a]=k[C][La]()[s](a)!=-1}var Ib={};function Jb(){return Hb("msie")&&!i[sa]}
function Kb(){if(k[Da]&&k.mimeTypes[y]){var a=k[Da]["Shockwave Flash"];if(a&&a.description)return a.description[r](/([a-zA-Z]|\s)+/,"")[r](/(\s)+r/,".")}else if(k[C]&&k[C][s]("Windows CE")>=0){a=3;for(var b=1;b;)try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+(a+1));a++}catch(c){b=g}return a[x]()}else if(Jb()){b=g;try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7")}catch(d){a=0;try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");a=6;b.AllowScriptAccess="always"}catch(e){if(a==
6)return a[x]()}try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(l){}}if(b){a=b.GetVariable("$version")[B](" ")[1];return a[r](/,/g,".")}}return"0"}function Lb(a,b){if(!(o[G]()<1.0E-4)){var c=o[G]();if(c<b){c=o[ma](c/b*a[y]);return a[c]}}return""}
var Mb=function(a){a.u_tz=-(new Date).getTimezoneOffset();a.u_his=i.history[y];a.u_java=k.javaEnabled();if(i[D]){a.u_h=i[D][Ka];a.u_w=i[D][ja];a.u_ah=i[D].availHeight;a.u_aw=i[D].availWidth;a.u_cd=i[D].colorDepth}if(k[Da])a.u_nplug=k[Da][y];if(k.mimeTypes)a.u_nmime=k.mimeTypes[y]},Nb=function(a,b){var c=b||L;if(a&&c.top!=c)c=c.top;try{return c[A]&&!c[A][Fa]?new ab(-1,-1):zb(c||i)}catch(d){return new ab(-12245933,-12245933)}},Ob=function(a,b){var c=a[y];if(c==0)return 0;for(var d=b||305419896,e=0;e<
c;e++){var l=a.charCodeAt(e);d^=(d<<5)+(d>>2)+l&4294967295}return d>0?d:4294967296+d},Pb=function(a){if(a==a.top)return 0;var b=[];b[q](a[A].URL);a[ya]&&b[q](a[ya]);var c=f;a=Nb(!c,a);b[q](a[ja][x]());b[q](a[Ka][x]());return Ob(b[I](""))},Qb=function(a){if(!a)return"";var b=[],c=0;for(a=a;a&&c<25;a=a[Ja],++c)b[q](a.id||"");return b[I]()};var Rb=Ra("0.005",0),Sb=Ra("1",0),Tb=Ra("0.01",0),Ub=Ra("0.001",0),Vb=Ra("0.006",0),Wb=Ra("0.008",0);var Xb=Sa("false",h),Yb=Sa("false",h),Zb=Sa("false",h),$b=Sa("false",h);var ac=function(a,b,c){b=Oa(b,J,a);a=i.onerror;i.onerror=b;try{c()}catch(d){c=d[x]();var e="";if(d.fileName)e=d.fileName;var l=-1;if(d.lineNumber)l=d.lineNumber;b=b(c,e,l);if(!b)throw d;}i.onerror=a};K("google_protectAndRun",ac);
var cc=function(a,b,c,d){if(o[G]()<0.01){var e=Ab;a=["http://",Ua("","pagead2.googlesyndication.com"),"/pagead/gen_204","?id=jserror","&jscb=",Xb?1:0,"&jscd=",Yb?1:0,"&context=",M(a),"&msg=",M(b),"&file=",M(c),"&line=",M(d[x]()),"&url=",M(e.URL[H](0,512)),"&ref=",M(e[wa][H](0,512))];a[q](bc());Gb(L,a[I](""))}return!Zb};K("google_handleError",cc);
var bc=function(){var a=["&client=",M(L.google_ad_client),"&format=",M(L.google_ad_format),"&slotname=",M(L.google_ad_slot),"&output=",M(L.google_ad_output),"&ad_type=",M(L.google_ad_type)];return a[I]("")};var N=function(){this.Z=[];this.qa=i;this.v=0},dc=function(a,b){this.fn=a;this.win=b};N[z].enqueue=function(a,b){this.Z[q](new dc(a,b||this.qa));ec(this)};N[z].Y=function(){this.v=1};N[z].$=function(){if(this.v==1)this.v=0;ec(this)};Pa(N[z],"nq",N[z].enqueue);Pa(N[z],"al",N[z].Y);Pa(N[z],"rl",N[z].$);var ec=function(a){a.qa[Ea](Oa(a.pa,a),0)};N[z].pa=function(){if(this.v==0&&this.Z[y]){var a=this.Z.shift();this.v=2;a.win[Ea](Oa(this.na,this,a),0);ec(this)}};N[z].na=function(a){this.v=0;a.fn()};var fc,gc,hc,ic,jc,kc,lc,mc=function(){lc=kc=jc=ic=hc=gc=fc=h;var a=lb();if(a)if(a[s]("Firefox")!=-1)fc=f;else if(a[s]("Camino")!=-1)gc=f;else if(a[s]("iPhone")!=-1||a[s]("iPod")!=-1)hc=f;else if(a[s]("iPad")!=-1)ic=f;else if(a[s]("Android")!=-1)jc=f;else if(a[s]("Chrome")!=-1)kc=f;else if(a[s]("Safari")!=-1)lc=f};mc();var nc=!!i.google_async_iframe_id,oc=nc&&i.parent||i;var O=function(a){this.C=a;this.W=[];this.V=0;this.I=[];this.ia=0;this.O=[];this.ha=h;this.f=this.ea="";this.ga=h},pc=function(a,b,c){var d=a.C[c],e=a.W;a.C[c]=function(l){if(l&&l[y]>0){var j=l[y]>1?l[1].url:g;e[q]([b,Ya(l[0].url),j])}d(l)}},qc=function(a){a.V++},rc=function(a,b){a.I[q](b)},sc="http://"+Va()+"/pagead/osd.js",tc=function(a){if(!a.ha){Fb(oc);Db(sc);a.ha=f}},uc=function(a,b){if(a.V>0)for(var c=a.C[A][Ba]("iframe"),d=a.ga?"google_ads_iframe_":"google_ads_frame",e=0;e<c[y];e++){var l=
c.item(e);l.src&&l[ya]&&l[ya][s](d)==0&&b(l,l.src)}},vc=function(a,b){var c=a.W;if(c[y]>0)for(var d=a.C[A][Ba]("a"),e=0;e<d[y];e++)for(var l=0;l<c[y];l++)if(d.item(e).href==c[l][1]){var j=d.item(e)[Ja];if(c[l][2])for(var p=j,t=0;t<4;t++){if(p.innerHTML[s](c[l][2])>0){j=p;break}p=p[Ja]}b(j,c[l][0]);c.splice(l,1);break}},xc=function(a,b){for(var c=0;c<a.I[y];c++){var d=a.I[c],e=wc(d);if(e)(e=a.C[A].getElementById("google_ads_div_"+e))&&b(e,d)}};O[z].T=function(a){vc(this,a);xc(this,a);uc(this,a)};
O[z].setupOsd=function(a,b,c){this.ia=a;this.ea=b;this.f=c};O[z].getOsdMode=function(){return this.ia};O[z].getEid=function(){return this.ea};O[z].getCorrelator=function(){return this.f};O[z].U=function(){return this.W[y]+this.V+this.I[y]};O[z].setValidOutputTypes=function(a){this.O=a};
O[z].registerAdBlockByType=function(a,b,c){if(this.O[y]>0){for(var d=0;d<this.O[y];d++)if(this.O[d]==a){this.ga=c;if(a=="js")pc(this,b,"google_ad_request_done");else if(a=="html")qc(this);else a=="json_html"&&rc(this,b)}tc(this)}};var wc=function(a){if((a=a[ra](/[&\?](?:slotname)=([^&]+)/))&&a[y]==2)return a[1];return""},yc=function(){var a=oc;a.__google_ad_urls||(a.__google_ad_urls=new O(a));return a.__google_ad_urls};K("Goog_AdSense_getAdAdapterInstance",yc);K("Goog_AdSense_OsdAdapter",O);
K("Goog_AdSense_OsdAdapter.prototype.numBlocks",O[z].U);K("Goog_AdSense_OsdAdapter.prototype.findBlocks",O[z].T);K("Goog_AdSense_OsdAdapter.prototype.getOsdMode",O[z].getOsdMode);K("Goog_AdSense_OsdAdapter.prototype.getEid",O[z].getEid);K("Goog_AdSense_OsdAdapter.prototype.getCorrelator",O[z].getCorrelator);K("Goog_AdSense_OsdAdapter.prototype.setValidOutputTypes",O[z].setValidOutputTypes);K("Goog_AdSense_OsdAdapter.prototype.setupOsd",O[z].setupOsd);
K("Goog_AdSense_OsdAdapter.prototype.registerAdBlockByType",O[z].registerAdBlockByType);var zc={google_ad_channel:"channel",google_ad_host:"host",google_ad_host_channel:"h_ch",google_ad_host_tier_id:"ht_id",google_ad_section:"region",google_ad_type:"ad_type",google_adtest:"adtest",google_allow_expandable_ads:"ea",google_alternate_ad_url:"alternate_ad_url",google_alternate_color:"alt_color",google_bid:"bid",google_city:"gcs",google_color_bg:"color_bg",google_color_border:"color_border",google_color_line:"color_line",google_color_link:"color_link",google_color_text:"color_text",google_color_url:"color_url",
google_contents:"contents",google_country:"gl",google_cpm:"cpm",google_cust_age:"cust_age",google_cust_ch:"cust_ch",google_cust_gender:"cust_gender",google_cust_id:"cust_id",google_cust_interests:"cust_interests",google_cust_job:"cust_job",google_cust_l:"cust_l",google_cust_lh:"cust_lh",google_cust_u_url:"cust_u_url",google_disable_video_autoplay:"disable_video_autoplay",google_ed:"ed",google_encoding:"oe",google_feedback:"feedback_link",google_flash_version:"flash",google_font_face:"f",google_font_size:"fs",
google_hints:"hints",google_kw:"kw",google_kw_type:"kw_type",google_language:"hl",google_page_url:"url",google_region:"gr",google_reuse_colors:"reuse_colors",google_safe:"adsafe",google_tag_info:"gut",google_targeting:"targeting",google_targeting_video_doc_id:"tvdi",google_ui_features:"ui",google_ui_version:"uiv",google_video_doc_id:"video_doc_id",google_video_product_type:"video_product_type"},Ac={google_ad_client:"client",google_ad_format:"format",google_ad_output:"output",google_ad_callback:"callback",
google_ad_height:"h",google_ad_override:"google_ad_override",google_ad_slot:"slotname",google_ad_width:"w",google_ctr_threshold:"ctr_t",google_image_size:"image_size",google_last_modified_time:"lmt",google_max_num_ads:"num_ads",google_max_radlink_len:"max_radlink_len",google_num_radlinks:"num_radlinks",google_num_radlinks_per_unit:"num_radlinks_per_unit",google_only_ads_with_video:"only_ads_with_video",google_rl_dest_url:"rl_dest_url",google_rl_filtering:"rl_filtering",google_rl_mode:"rl_mode",google_rt:"rt",
google_skip:"skip"},Bc={google_only_pyv_ads:"pyv",google_with_pyv_ads:"withpyv"};var Cc=n,P=k,Q=i;
function Dc(){var a=Cc[na],b=o[ka]((new Date)[Aa]()/1E3),c=Q.google_analytics_domain_name;c=typeof c=="undefined"?Ec("auto"):Ec(c);var d=a[s]("__utma="+c+".")>-1,e=a[s]("__utmb="+c)>-1,l=a[s]("__utmc="+c)>-1,j={},p=!!Q&&!!Q.gaGlobal;if(d){a=a[B]("__utma="+c+".")[1][B](";")[0][B](".");j.sid=e&&l?a[3]+"":p&&Q.gaGlobal.sid?Q.gaGlobal.sid:b+"";j.vid=a[0]+"."+a[1];j.from_cookie=f}else{j.sid=p&&Q.gaGlobal.sid?Q.gaGlobal.sid:b+"";j.vid=p&&Q.gaGlobal.vid?Q.gaGlobal.vid:(o[ka](o[G]()*2147483647)^Fc()&2147483647)+
"."+b;j.from_cookie=h}j.dh=c;j.hid=p&&Q.gaGlobal.hid?Q.gaGlobal.hid:o[ka](o[G]()*2147483647);return Q.gaGlobal=j}function Fc(){var a=Cc[na]?Cc[na]:"",b=Q.history[y],c,d=[P.appName,P.version,P.language?P.language:P.browserLanguage,P.platform,P[C],P.javaEnabled()?1:0][I]("");if(Q[D])d+=Q[D][ja]+"x"+Q[D][Ka]+Q[D].colorDepth;else if(Q.java){c=java.awt.Toolkit.getDefaultToolkit().getScreenSize();d+=c[D][ja]+"x"+c[D][Ka]}d+=a;d+=Cc[wa]?Cc[wa]:"";for(a=d[y];b>0;)d+=b--^a++;return Gc(d)}
function Gc(a){var b=1,c=0,d;if(!(a==ca||a=="")){b=0;for(d=a[y]-1;d>=0;d--){c=a.charCodeAt(d);b=(b<<6&268435455)+c+(c<<14);c=b&266338304;b=c!=0?b^c>>21:b}}return b}function Ec(a){if(!a||a==""||a=="none")return 1;if("auto"==a){a=Cc[qa];if("www."==a[H](0,4))a=a[H](4,a[y])}return Gc(a[La]())};function Hc(a,b,c,d){this._value_=a;this._expires_=b;this._path_=c;this._domain_=d;if(!this._path_)this._path_="/";if(this._domain_==g)this._domain_=n[qa]}fa(Hc[z],function(){return"[GA_GoogleCookieInfo: value="+this._value_+", expires="+this._expires_+", path="+this._path_+"]"});function Ic(){this.w=Jc(this);this.Q=h;if(!this.w)this.Q=Kc(this)}Ic[z].P="__gads=";Ic[z].D="GoogleAdServingTest=";Ic[z].M=function(a){this.q=a._cookies_[0];if(this.q!=g){this.w=this.q._value_;Lc(this)}};Pa(Ic[z],"setCookieInfo",Ic[z].M);
var Mc=function(a,b){var c=(new Date)[ia](),d=new Date;d.setTime(c+b);return d},Nc=function(a){var b=15552E6;a=Mc(a,b);b="ID=12345:T="+b;var c="/",d=n[qa];return new Hc(b,a[ia](),c,d)},Oc="http://"+Ua("","partner.googleadservices.com")+"/gampad/cookie.js?callback=_GA_googleCookieHelper.setCookieInfo",Pc=function(a,b){if(!(a.w||!a.Q)){var c="script",d=n[qa];d=Oc+"&client="+M(b)+"&domain="+M(d);n[u]("<"+c+' src="'+d+'"></'+c+">")}},Kc=function(a){n.cookie=a.D+"Good";var b=Qc(a,
a.D);if(b=b=="Good"){var c=Mc(a,-1);n.cookie=a.D+"; expires="+c.toGMTString()}return b},Jc=function(a){return a=Qc(a,a.P)},Qc=function(a,b){var c=n[na],d=c[s](b),e="";if(d!=-1){d=d+b[y];e=c[s](";",d);if(e==-1)e=c[y];e=c[H](d,e)}return e},Lc=function(a){if(a.q!=g)if(a.w){var b=new Date;b.setTime(1E3*a.q._expires_);var c=a.q._domain_;a=a.P+a.w+"; expires="+b.toGMTString()+"; path="+a.q._path_+"; domain=."+c;n.cookie=a}};function Rc(a,b){try{return a.top[A].URL==b.URL}catch(c){}return h};var Sc=function(a){var b="google_unique_id";if(a[b])++a[b];else a[b]=1;return a[b]};var Tc=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^/?#]*)@)?([\\w\\d\\-\\u0100-\\uffff.%]*)(?::([0-9]+))?)?([^?#]+)?(?:\\?([^#]*))?(?:#(.*))?$"),Uc=function(a){return a&&da(a)};var Vc=function(a){this.oa=(this.R=a&&a.GA_jstiming)&&this.R.load};Vc[z].tick=function(a,b){this.oa.tick(a,b)};Vc[z].report=function(a){var b={};b.e=a;this.R.report(this.oa,b)};var Wc=function(){};Qa(Wc,Vc);Wc[z].tick=function(){};Wc[z].report=function(){};var Xc=function(a,b,c,d){if(c<=4){b=b+"_"+c;d?a.tick(b,d+"_"+c):a.tick(b)}};var Yc=function(a,b){var c=0,d=[];a&&d[q](a);if(b){var e=Qb(b);e&&d[q](e)}if(d[y]>0)c=Ob(d[I](":"));return c[x]()};var Zc=L&&o[G]()<Rb&&L.GA_jstiming&&L.GA_jstiming.load&&L.location.protocol=="http:"?new Vc(L):new Wc(L);Zc.tick("js_load");function R(a){return typeof a=="function"}function $c(a,b){if(typeof a!="string"||a[y]==0)return g;else if(typeof b!="string"||b[y]==0)return g;return ad(S(),a,b)}K("GA_googleAddSlot",$c);function _GA_googleInitializeAdEngine(a){if(!W()){bd(cd(a));dd(W())}}K("_GA_googleInitializeAdEngine",_GA_googleInitializeAdEngine);
function ed(){S().ra=f;_GA_googleInitializeAdEngine(g);var a=W().g;a=="sync"||a=="sync_sra"?W().j():fd(S())}K("GA_googleFetchAds",ed);function gd(){_GA_googleInitializeAdEngine("iframe");Pc(i._GA_googleCookieHelper,i.GS_googleGetIdsForAdSenseService())}K("GA_googleUseIframeRendering",gd);function hd(){var a=i.GA_googleEnv[w]("google_ad_impl");a==g&&i.GA_googleEnv.setParameter("google_ad_impl","sync_sra")}K("GA_googleUseSyncSRARendering",hd);
function id(a){i.GA_googleEnv.setParameter("google_domain_reset_url",a)}K("GA_googleDomainResetUrl",id);function jd(a){var b=Bb(Ab);kd(S(),a,b);if(W()!=g)if(W().g!="iframe"){if(ld(W()))if(W().N){b=md(S(),a);if(b==g)return;else if(!b._enabled_)return}else return;else if(nd(W(),a)!=g&&!W().l)return;W().n(a)}}K("GA_googleFillSlot",jd);function od(a,b,c,d){a=a||"";b=b||"";c=c||0;d=d||0;var e=Bb(Ab);kd(S(),b,e);if(W()!=g)if(W().g=="iframe"){ad(S(),a,b);a=new pd(c,d,h,f);qd(S(),b,a);W().n(b)}}
K("GA_googleFillSlotWithSize",od);function rd(){sd(new td(zc));bd(g)}K("GA_googleResetAll",rd);i.google_noFetch=h;function ud(){i.google_noFetch=f}K("GA_googleNoFetch",ud);function vd(){i.google_delayFetch=f}K("GA_googleDelayFetch",vd);function pd(a,b,c,d){this._width_=a;this._height_=b;this._expandable_=c;this._enabled_=d}fa(pd[z],function(){return"[GA_GoogleAdSlotAttr: width="+this[Ga]+", height="+this[pa]+", expandable="+this._expandable_+", enabled="+this._enabled_+"]"});
function wd(a){var b={};a=a[B]("?");a=a[a[y]-1][B]("&");for(var c=0;c<a[y];c++){var d=a[c][B]("=");if(d[0])try{b[d[0][La]()]=d[y]>1?i.decodeURIComponent?da(d[1][r](xd," ")):unescape(d[1]):""}catch(e){}}return b}function yd(a){a=a||n.URL;this.la=wd(a)}yd[z].getParameter=function(a){return a==g?g:this.la[a]};yd[z].setParameter=function(a,b){this.la[a]=b};var zd=function(){if(!$b)return"http://"+Ua("","pubads.g.doubleclick.net");return"https://"+Ua("","securepubads.g.doubleclick.net")};
function Ad(a){return a[r](/&/g,"&amp;")[r](/</g,"&lt;")[r](/>/g,"&gt;")[r](/\"/g,"&quot;")}function Bd(){this.G=g;this.ma=h;this.Aa=(new Date)[ia]()}
var Dd=function(a,b){if(a.G==g)if(!a.ma){a.G=i.open("","GoogleAdCapture","width=1100, height=1400, status=no, resizable=yes, scrollbars=yes,menubar=yes, toolbar=yes");if(a.G){var c=a.G[A],d=[];d[q]('<html>\n<head>\n<title>Google Ad Capture Window</title>\n<script>function displayTime(id, start){var delta=(new Date()).valueOf() - start;document.getElementById(id).innerHTML=""+delta;}var pageStartTime = (new Date()).valueOf();var slotStartTime = 0;window.onload=function(){displayTime("total", pageStartTime);};<\/script></head>\n<body>\n');d[q]("<p>Google Ad Capture Window</p>");
for(var e in b)R(b[e])||d[q](Cd(a,e,b[e]));d[q]("<p>Time blocked rendering ads (ms): <label id='blocked'></label>");d[q]("<script>displayTime('blocked', pageStartTime);<\/script>");d[q]("<p>Total Page Load Time (ms): <label id='total'></label>");d[q]("</body>\n</html>");d=d[I]("\n");(e=i.GA_googleEnv[w]("google_capture_norender")!=g)?c[u](Ad(d)):c[u](d);c.close()}else a.ma=f}},Cd=function(a,b,c){a="<script>slotStartTime = (new Date()).valueOf();<\/script>";var d="<p>Slot "+b+"</p>";c=c==g||c[v]==
g?"No ad":c[v];var e="<p>Slot Time (ms): <label id='"+b+"'></label>";b='<script>displayTime("'+b+'", slotStartTime);<\/script>';return a+d+"\n"+c+"\n"+e+b};function Ed(a){this.d={};this.F=a}var Fd=function(a,b,c,d){if(b){c||(c="");if(b=="google_gl")b="google_country";else if(b=="google_region")b="google_section";if(b in a.F)if((d=typeof d=="undefined"||d)||!a.d[b])a.d[b]=c}},Gd=function(a,b){for(var c in b.d)R(b.d[c])||a.d[c]||(a.d[c]=b.d[c])};Ed[z].getAttribute=function(a){return this.d[a]};
Ed[z].h=function(){var a=[];for(var b in this.d)if(!R(this.d[b])){var c=zc[b]||Ac[b]||Bc[b]||g,d=this.d[b];c&&d&&a[q](c+"="+M(d))}return a[I]("&")};
var Id=function(a,b,c,d){a=Hd(a,b,c,d);b=[];a[0]&&a[0][y]>0&&b[q](a[0][I]("&"));a[1]&&a[1][y]>0&&b[q]("sps="+a[1][I]("|"));return b[I]("&")},Hd=function(a,b,c,d){var e=[],l=[];b=b.d;for(var j in d)if(!R(j)){var p=d[j];if(p){var t="";if(b[j]!=g)t=M(b[j]);var ta=[],T=-1,U=-1;for(var V in a)if(!R(a[V])){++T;if(c[V]==g)ta[q]("");else{var gb=c[V].d;if(gb[j]!=g){ta[q](M(M(gb[j])));U=T}else ta[q]("")}}if(U>=0){T=M(t);t=[];t[q](T);for(T=0;T<=U;++T)t[q](ta[T]);l[q](p+","+t[I](","))}else t&&e[q](p+"="+t)}}a=
[];a[q](e);a[q](l);return a};function Jd(a,b){this.L=a;this.s=b;this.aa=0;this.xa=this.S=this.X=h;this.va=this.wa=this.fa=this.sa=g}var Kd=function(a){a.S=f;a.sa=(new Date)[ia]()},Ld=function(a){a.fa=(new Date)[ia]()},Md=function(a){a.xa=f;a.wa=(new Date)[ia]()},Nd=function(a){a.va=(new Date)[ia]()};fa(Jd[z],function(){return"[GA_GoogleAdSlot: pubid="+this.L+", name="+this.s+", loaded="+this.X+", tries="+this.aa+"]"});
function td(a){this.a={};this.c=[];this.r={};this.F=a;this.ka=new Ed(this.F);this.B={};this.ra=h;this.o=g;this.ca={}}
var ad=function(a,b,c){b=new Jd(b,c);return a.a[b.s]=b},Od=function(a,b){var c=[];for(var d in a.a)if(!R(a.a[d])){if(b){var e=md(a,d);if(e==g||!e._enabled_)continue}e=a.a[d];e.S||c[q](e)}return c},Pd=function(a,b){return Od(a,b)[y]},Qd=function(a){var b=[];for(var c in a.a){var d=a.a[c];R(d)||d.S&&d.fa==g&&b[q](c)}return b},Rd=function(a){var b=0;for(var c in a.a)if(!R(a.a[c])){var d=md(a,c);d!=g&&d._enabled_&&b++}return b},Sd=function(a){for(var b in a.a)if(!R(a.a[b])){var c=a.a[b];Kd(c)}},Td=function(a,
b){var c=a.a[b];Kd(c)},Ud=function(a,b){var c=a.a[b];Ld(c)},Vd=function(a,b){var c=a.a[b];Md(c)},Wd=function(a,b){var c=a.a[b];Nd(c);Xc(Zc,"ga_render",a.c[y],"ga_srt")},Xd=function(a){var b=0;for(var c in a.a)R(a.a[c])||b++;return b};fa(td[z],function(){var a="[AdData:",b=[];for(var c in this.a)R(this.a[c])||b[q](this.a[c][x]());for(var d in this.r)R(this.r[d])||b[q]("["+d+","+this.r[d]+"]");a+=b[I]();a+="]";return a});
var Yd=function(a,b){return a.a[b]},Zd=function(a,b,c){if(!(b==g||b[y]==0)){if(c==g||c[y]==0)c="";var d=a.r[b];a.r[b]=d==g?c:d+","+c}};function $d(a,b){Zd(S(),a,b)}K("GA_googleAddAttr",$d);var ae=function(a,b,c){Fd(a.ka,b,c)};function be(a,b){ae(S(),a,b)}K("GA_googleAddAdSensePageAttr",be);var ce=function(a){return a.ka},de=function(a,b,c,d){if(!(b==g||b[y]==0)){if(W()==g||W().g!="iframe"){var e=a.a[b];if(e==g)return}e=a.B[b];if(e==g)a.B[b]=new Ed(a.F);Fd(a.B[b],c,d)}};
function ee(a,b,c){de(S(),a,b,c)}K("GA_googleAddAdSenseSlotAttr",ee);
var fe=function(a,b){return a.B[b]},kd=function(a,b,c){a.ca[b]=c},ge=function(a,b){return a.ca[b]},he=function(){var a=zd();return a+"/gampad/slotdata.js?callback=GA_googleSetAdSlotAttributes"},fd=function(a){if(a.o!=g)W().j();else{var b=[];for(var c in a.a)R(a.a[c])||b[q](c);a=i.GS_googleGetIdsForAdSenseService();b=he(i)+"&client="+escape(a)+"&page_slots="+escape(b[I]());n[u]("<script src = '"+b+"'><\/script>")}},ie=function(a,b){a.o=b;W().N=f;W().j()};function je(a){ie(S(),a)}
K("GA_googleSetAdSlotAttributes",je);var qd=function(a,b,c){if(a.o==g)a.o={};a.o[b]=c;W().N=f},md=function(a,b){return a.o!=g?a.o[b]:g};function ke(a,b,c){if(!c||c<0||c>1)c=0;this.ya=o[G]()<c;this.ta=a;this.ba=b+"/pagead/gen_204?id="+M(a);this.ua=[]}
var X=function(a,b,c){if(b&&b[ra](/^\w+$/)&&c)a.ba+="&"+b+"="+M(c)},le=function(a){var b=S();for(var c in b.a){var d=b.a[c];if(!R(d)&&d.L!=g){X(a,"pub_id",d.L);break}}X(a,"nslots",Xd(b)[x]());X(a,"pub_url",n.URL);X(a,"pub_ref",n[wa])},me=function(a){if(!a.ya||!a.ta||!a.ba)return h;var b=new Image;b.src=a.ba;a.ua[q](b);return f};function Y(a){this.i=g;this.o={};this.p=this.b="";this.l=a;this.m=this.K=this.t=h;this.g="sync";this.za=zc;this.u=f;this.da=this.N=h}
var dd=function(a){a.t=i.GA_googleEnv[w]("google_nofetch")!=g||i.google_noFetch;a.K=i.GA_googleEnv[w]("google_norender")!=g;a.m=i.GA_googleEnv[w]("google_capture")!=g||i.GA_googleEnv[w]("google_capture_norender")!=g;if(a.m)a.K=f;ne(a,i);a.b=a.p;var b=Oa(a.ja,a);oe(a,i,b)},pe=function(a){a.da=f},oe=function(a,b,c){if(b[xa]){b[xa]("onload",c);return f}if(b[va]){b[va]("load",c,h);return f}return h};Y[z].H=function(){this.m&&Dd(i.GA_googleAdCapture,this.i)};
var qe=function(a){if(a.g=="sync_sra"){var b=S(),c=Xd(b);b=b.c[y];if(c!=b){a.J=new ke("sra_mismatch",zd(),Ub);X(a.J,"correlator",a.f);X(a.J,"fslots",b[x]());le(a.J);me(a.J)}}},re=function(a){Zc.tick("ga_onload");Zc.report(a.g)},se=function(a){var b=Qd(S());if(b[y]>0){a.A=new ke("missing_cb",zd(),Tb);X(a.A,"pending",b[I]());X(a.A,"correlator",a.f);X(a.A,"impl",a.g);le(a.A);me(a.A)}};Y[z].ja=function(){re(this);this.H();qe(this);se(this)};
var ne=function(a){var b=i.GA_googleEnv[w]("google_ad_url");if(b==g||b[y]==0)a.p=zd()+"/gampad/ads?";else{if(b[oa](b[y]-1)!="?")b+="?";a.p=b}};Y[z].k=function(){};
var nd=function(a,b){return a.i!=g?a.i[b]:g},te=function(){var a=k[C],b=a[s]("MSIE ");return b==-1?0:parseFloat(a[H](b+5,a[s](";",b)))},xd=/\+/g,ue=function(a,b){b=b[La]();if(b[H](0,3)!="ca-")b="ca-"+b;return b},$=function(a,b,c){c!=g&&Z(a,b,M(c[x]()))},Z=function(a,b,c){if(c!=g&&c!="")a.b+=a.b[oa](a.b[y]-1)!="?"?"&"+b+"="+c:b+"="+c},ve=function(a,b){for(var c=Od(S(),a.u),d=[],e=[],l=[],j=c[y],p=0;p<j;p++){var t=c[p];l[q](t.s);if(!(b!=g&&b!=t.s)){d[q](t.s);e[q](ue(a,t.L))}}$(a,"client",e[0]);if(a.l)l[y]>
0&&$(a,"page_slots",l[I]());else{$(a,"slotname",d[I]());S().c[y]>0&&$(a,"page_slots",S().c[I]())}},we=function(a,b,c){if(c!=g){a=b.lastIndexOf("?");a=b[s]("google_preview=",a);c=b[s]("&",a);if(c==-1){c=b[y]-1;a-=1}return b[H](0,a)+b[H](c+1,b[y])}return b},xe=function(a,b,c){if(Rc(b,c))return c.URL;return c[wa]},ze=function(a,b,c){if(ye(a,b,c)!=c.URL)return c[qa];return""},ye=function(a,b,c){var d=ce(S()).getAttribute("google_page_url");if(d)return d;return xe(a,b,c)},Ae=function(a,b,c,d){$(a,"url",
we(a,ye(a,i,n),i.GA_googleEnv[w]("google_preview")));$(a,"ref",n[wa]);$(a,"lmt",(Date.parse(n.lastModified)/1E3)[x]());Z(a,"dt",b[Aa]());if(n[Fa]){b=n[Fa].scrollHeight;var e=n[Fa].clientHeight;e&&b&&$(a,"cc",o[ka](e*100/b)[x]())}b=f;if(b=Nb(b)){$(a,"biw",b[ja]);$(a,"bih",b[Ka])}b=Sc(i);$(a,"ifi",b);b=Pb(i);b!=0&&$(a,"ifk",b[x]());b=Yc(c,ge(S(),c));$(a,"adk",b);b=i.GA_googleEnv[w]("deb");b!=g&&$(a,"deb",b);b=i.GA_googleEnv[w]("haonly");b!=g&&$(a,"haonly",b);b=ce(S());k[C][s]("MSIE ")>0&&Fd(b,"google_encoding",
n.charset,h);e="";if(d)e=Id(S().a,b,S().B,a.za);else{c=fe(S(),c);if(c==g)c=b;else Gd(c,b);e=c.h()}if(e)a.b+="&"+e},Be=function(a,b,c){var d=S().r,e=[];for(var l in d)R(d[l])||e[q](M(l)+"="+M(d[l]));$(a,"cust_params",e[I]("&"));if(b._GA_googleCookieHelper){$(a,"cookie",b._GA_googleCookieHelper.w);b._GA_googleCookieHelper.Q&&$(a,"cookie_enabled","1")}(b=ze(a,b,c))&&$(a,"cdm",b)},Ce=function(a){Dc();var b=i;Z(a,"ga_vid",b.gaGlobal.vid);Z(a,"ga_sid",b.gaGlobal.sid);Z(a,"ga_hid",b.gaGlobal.hid);Z(a,"ga_fc",
b.gaGlobal.from_cookie);$(a,"ga_wpids",b.google_analytics_uacct)},De=function(a,b){for(var c in b){var d=b[c];R(d)||Z(a,c,d)}},Ge=function(a){var b=[];if(Na(i.GS_googleGetExpIdsForAdSense)=="function"){var c=i.GS_googleGetExpIdsForAdSense();c&&b[q](c)}c=Ee(a.f[x]());var d=Fe();c&&b[q](c);d&&b[q](d);b[y]>0&&$(a,"eid",b[I]())};
Y[z].h=function(a){this.k();Ge(this);var b=new Date;ve(this,a);Be(this,i,n);i.GA_googleEnv[w]("google_preview")!=g&&Z(this,"gct",i.GA_googleEnv[w]("google_preview"));Ce(this);Ae(this,b,a,this.l);a={};Mb(a);De(this,a);Z(this,"flash",Kb());this.b=this.b[H](0,2E3);this.b=this.b[r](/%\w?$/,"");if(this.da){a=this.g=="iframe"||this.g=="fallback"?"html":"json_html";yc().registerAdBlockByType(a,this.b,f)}return this.b};
var ld=function(a){return a.u},He=function(a,b){var c=b.getAttribute("id");return c=c.substr(18,c[y]-18)},Ie=function(a,b,c,d){a='<ins style="position:relative;width:'+b+"px;height:"+c+'px;border:none;display:block;">'+d+"</ins>";return b='<ins style="position:relative;width:'+b+"px;height:"+c+'px;border:none;display:inline-table;">'+a+"</ins>"},Ke=function(a,b,c,d,e,l){var j="google_ads_iframe_"+b,p=[];b="google_ads_div_"+b;var t="border:0px;";if(Je(i))t+="left:0;position:absolute;top:0;";p[q]("<iframe id=",
j," name=",j,' width="',e,'" height="',l,'" vspace="0" hspace="0" allowtransparency="true" ',"scrolling=",a.m?'"auto"':'"no"',' marginwidth="0" marginheight="0" frameborder="0" ','style="',t,'"',' src="',Ad(c),'"');d!=g&&p[q](' onload="',d,'"');p[q]("></iframe>");c=[];p=p[I]("");c[q]("<div id=",b,">");Je(i)?c[q](Ie(a,e,l,p)):c[q](p);c[q]("</div>");a=c[I]("");n[u](a)},Le=function(a,b,c){var d=nd(a,c),e=d[Ga],l=d[pa];d=d[v];var j=n[ua]("iframe");j.id="google_ads_iframe_"+c;j.name="google_ads_iframe_"+
c;ea(j,e);ga(j,l);j.vspace=0;j.hspace=0;j.allowTransparency="true";j.scrolling="no";j.marginWidth=0;j.marginHeight=0;j.frameBorder=0;j[E].border=0;b=n.getElementById(b);if(Je(i)){j[E].position="absolute";j[E].top=0;j[E].left=0;var p=n[ua]("ins");ea(p[E],e+"px");ga(p[E],l+"px");p[E].border=0;p[E].display="block";p[E].position="relative";var t=n[ua]("ins");ea(t[E],e+"px");ga(t[E],l+"px");t[E].border=0;t[E].display="inline-table";t[E].position="relative";p[ha](j);t[ha](p);b[ha](t)}else b[ha](j);if(a.m){j[za][A][u](Ad(d));
j.scrolling="auto"}else j[za][A][u](d);Je(i)?j[za][A][u]("<script>document.close();<\/script>"):j[za][A].close();Wd(S(),c)};function Me(a,b){Le(W(),a,b)}K("GA_googleCreateDomIframe",Me);
var Ne=function(){var a=[],b=n[Ba]("base");if(b)for(var c=0,d=b[y];c<d;++c){var e=b[c],l=e.getAttribute("target");if(l){a[q]({baseElement:e,originalTagValue:l});e.removeAttribute("target")}}return a},Oe=function(a){if(a)for(var b=0,c=a[y];b<c;++b){var d=a[b];d.baseElement.setAttribute("target",d.originalTagValue)}},Pe=function(a){var b="http://"+Va()+"/pagead/inject_object_div.js";if(m(te(),10)>6)return h;if(a[s](b)<0)return h;return f},Qe=function(a,b,c){if(a.m)c=Ad(c);a=Ne();i.frames[b[ya]].contents=
c;b.src=Pe(c)?'javascript:document.write(window["contents"]);document.close();':'javascript:window["contents"]';Oe(a)},Re=function(a,b,c){var d=He(a,b);try{var e=b[za]?b[za][A]:b.contentDocument;if(e==g)if(n.implementation&&n.implementation.createDocument)e=n.implementation.createDocument("",d,g);else if(typeof ActiveXObject!="undefined")e=new ActiveXObject("Msxml.DOMDocument");else return h;e.open("text/html","replace");a.m?e[u](Ad(c)):e[u](c);e.close()}catch(l){return h}return f},Se=function(a,
b){var c=He(a,b),d=Yd(S(),c);if(!d.X){d.X=f;d=nd(a,c);var e=b[Ja];if(d==g||d[v]==g)e.removeChild(b);else if(d._expandable_&&!(d[Ha]&&d._is_3pas_))e.innerHTML=d[v];else d._is_3pas_?Qe(a,b,d[v]):Re(a,b,d[v]);Wd(S(),c)}},Te=function(a,b){var c="google_ads_div_"+b;c="<div id="+c+">";var d=nd(a,b);if(d!=g){c+=d[v];c+="\n</div>\n";n[u](c);Wd(S(),b)}},Ue=function(a,b){var c="google_ads_div_"+b,d="<div id="+c+">";d+="\n</div>\n";n[u](d);return c},Ve=function(a){if(!a.u)return f;if(Pd(S(),a.u)>0)return f;
else if(Rd(S())==0)return h},We=function(a,b){Xc(Zc,"ga_srt",S().c[y],"_ga_start");if(a.i==g){a.i=b;for(var c in b)R(b[c])||Ud(S(),c)}else for(c in b)if(!R(b[c])){a.i[c]=b[c];Ud(S(),c)}var d=h;for(c in b)if(!R(b[c])){var e=b[c];if(d){e._cookies_=[Nc(i._GA_googleCookieHelper)];d=h}e!=g&&e._cookies_!=g&&i._GA_googleCookieHelper.M(e)}};function Xe(a){We(W(),a)}K("GA_googleSetAdContentsBySlot",Xe);function Ye(a){Y[F](this,a);this.u=h;this.f=(new Date)[Aa]();this.g=a?"sync_sra":"sync"}Qa(Ye,Y);
Ye[z].k=function(){this.b=this.p;$(this,"correlator",this.f[x]());Z(this,"output","json_html");Z(this,"callback","GA_googleSetAdContentsBySlotForSync");this.l?Z(this,"impl","ss"):Z(this,"impl","s");Ze(this,S().c);this.l||$e(this,S().c,this.i)};
var Ze=function(a,b){for(var c=0,d=f,e=0;e<b[y];++e){var l=a.i&&a.i[b[e]];if(l)if(l[Ha]==ca){d=h;break}else c=2*c+(l[Ha]?1:0)}d&&Z(a,"prev_afc",c)},$e=function(a,b,c){if(b&&c){for(var d=[],e=[],l=b[y]-1,j=0;j<l;j++){var p=b[j];if((p=c[p])&&p._cids_&&p._a2ids_){d[q](p._cids_[0]);e[q](p._a2ids_[0])}else{d[q]("");e[q]("")}}if(d[y]>0){b=d[I](",");e=e[I](",");$(a,"a2ids",e);$(a,"cids",b)}}},af=function(a,b){var c=S().a;c=c[b];if(c!=g)if(!a.t){a.h(c.s);Td(S(),b);n[u]("<script src = '"+a.b+"'><\/script>")}},
cf=function(a,b){We(a,b);if(a.l)if(S().c[y]==1){var c=S().c[0];bf(a,c);return}for(c in b)R(b[c])||bf(a,c)};function df(a){cf(W(),a)}K("GA_googleSetAdContentsBySlotForSync",df);Ye[z].j=function(){Ve(this)};var ef=function(a){a.h(g);n[u]("<script src = '"+a.b+"'><\/script>");Sd(S())};Ye[z].n=function(a){S().c[q](a);Xc(Zc,"_ga_start",S().c[y]);if(this.l)S().c[y]==1?ef(this):bf(this,a);else af(this,a)};
var ff=function(a,b,c){if(b.google_js_backfill){a="script";c[u]("<"+a+' src="'+Cb+'"></'+a+">")}},bf=function(a,b){gf(a,i,n,b)},gf=function(a,b,c,d){var e=Yd(S(),d);if(e!=g){e=nd(a,d);Vd(S(),d);if(e==g||e._empty_){ff(a,b,c,d);Wd(S(),d)}else if(a.K&&!a.m)Wd(S(),d);else if(e._snippet_&&!e[Ha]&&!a.m)Te(a,d);else if(b[Ia][C][s]("MSIE ")>0){c="GA_googleSyncAdSlotLoaded(this);";var l="about:blank";if(b=b.GA_googleEnv[w]("google_domain_reset_url")){var j=Uc(b[ra](Tc)[3]||g);if(j===g||j[s](n[qa])>=0)l=b}Ke(a,
d,l,c,e[Ga],e[pa])}else{a=Ue(a,d);c[u]("<script>GA_googleCreateDomIframe('"+a+"' ,'"+d+"');<\/script>")}}},hf=function(a,b){var c=He(a,b);Yd(S(),c);Se(a,b)};function jf(a){hf(W(),a)}K("GA_googleSyncAdSlotLoaded",jf);function kf(a){Y[F](this,a);this.f=(new Date)[Aa]();this.g="async"}Qa(kf,Y);kf[z].k=function(){this.b=this.p;lf(this);$(this,"correlator",this.f[x]());Z(this,"output","json_html");Z(this,"callback","GA_googleSetAdContentsBySlot");Z(this,"impl","a")};
var lf=function(a){a.delay=500;var b=i.GA_googleEnv[w]("google_async_delay");if(b!=g)a.delay=1E3*b};kf[z].j=function(){if(Ve(this))this.t||i[Ea]("GA_googleReallyFetchAds();",20)};var mf=function(a){if(Pd(S(),a.u)!=0){var b=n[Ba]("head")[0];if(a.l){var c=n[ua]("script");c.src=a.h(g);b[ha](c);Sd(S())}else{var d=S().a;for(var e in d)if(!R(d[e])){c=n[ua]("script");c.src=a.h(e);b[ha](c);Td(S(),e)}}}};function nf(){mf(W())}K("GA_googleReallyFetchAds",nf);
kf[z].n=function(a){var b=Yd(S(),a);if(b!=g){S().c[q](a);b="GA_googleAsyncAdSlotLoaded(this);";var c=md(S(),a);Ke(this,a,"about:blank",b,c[Ga],c[pa])}};var pf=function(a,b){var c=He(a,b);Yd(S(),c);!a.t&&!a.K&&of(a,b)};function qf(a){pf(W(),a)}K("GA_googleAsyncAdSlotLoaded",qf);var of=function(a,b){var c=He(a,b),d=Yd(S(),c);if(a.i==g||a.i[c]==g){if(!(d.aa>30)){i[Ea](function(){of(W(),b)},a.delay);d.aa++}}else Se(a,b)};kf[z].H=function(){};
function rf(a){Y[F](this,a);this.f=(new Date)[Aa]();this.g="fallback"}Qa(rf,Y);rf[z].k=function(){this.b=this.p;$(this,"correlator",this.f[x]());Z(this,"output","html");Z(this,"impl","fb")};rf[z].j=function(){Ve(this)};rf[z].z=function(a){if(this.l){this.h(g);a=this.b+"&currentslot="+M(a)}else a=this.h(a);return a};rf[z].n=function(a){var b=md(S(),a);if(b!=g){S().c[q](a);if(!this.t){var c=this.z(a);Ke(this,a,c,g,b[Ga],b[pa])}}};
function sf(a){Y[F](this,a);this.f=(new Date)[Aa]();this.N=f;this.g="iframe"}Qa(sf,Y);sf[z].k=function(){this.b=this.p;$(this,"correlator",this.f[x]());Z(this,"output","html");Z(this,"impl","ifr")};sf[z].j=function(){Ve(this)};sf[z].z=function(a){if(this.l){this.h(g);a=this.b+"&currentslot="+M(a)}else a=this.h(a);return a};sf[z].n=function(a){var b=md(S(),a);if(b!=g){S().c[q](a);if(!this.t){var c=this.z(a);Ke(this,a,c,g,b[Ga],b[pa])}}};
var tf=function(){if(Jb()){var a=te();return a<=5}else if(Hb("firefox")){var b=k[C][s]("Firefox")+8;a=m(k[C][oa](b),10);b=k[C][la](b);return a<1}else if(Hb("safari")){b=k[C][s]("Safari")+7;b=k[C][la](b);a=m(b,10);return a<412}else if(i[sa]!=g){b=k[C][s]("Opera")+6;b=k[C][la](b);a=m(b,10);return a<9}else if(!Jb()&&!Hb("safari")&&Hb("mozilla")){b=k[C][s]("Netscape")+9;b=k[C][la](b);a=m(b,10);return a<7}else return f},uf=function(){if(Jb()){var a=te();return a>5}else if(Hb("firefox")){a=k[C][s]("Firefox")+
8;var b=m(k[C][oa](a),10);k[C][la](a);return b>1}return h},vf=function(){if(tf())return"fallback";else if(i.google_delayFetch&&uf())return"async";return"sync"},cd=function(a){var b=g;if(typeof a!="undefined"&&a!=g)b=a;else{b=i.GA_googleEnv[w]("google_ad_impl");if(b==g)b=vf()}switch(b){case "async":return new kf(h);case "sync":return new Ye(h);case "sync_sra":return new Ye(f);case "fallback":return new rf(h);case "iframe":return new sf(h);default:return new rf(h)}},wf;
function S(){wf||(wf=new td(zc));return wf}function sd(a){delete wf;wf=a}var xf;function W(){xf||(xf=g);return xf}function bd(a){delete xf;xf=a}if(typeof i.GA_googleEnv=="undefined")i.GA_googleEnv=new yd;if(typeof i.GA_googleAdCapture=="undefined")i.GA_googleAdCapture=new Bd;if(i._GA_googleCookieHelper==g)i._GA_googleCookieHelper=new Ic(g);
function Ee(a){var b=yc(),c=b.getEid();if(c==""){if(c=yf(i)){var d=b.getOsdMode();if(c=="36815006"||c=="36813008"){b.setValidOutputTypes(["html","json_html"]);d=c=="36815006"?1:0}b.setupOsd(d,c,a);(a=W())&&pe(a)}}else if(c!="36815006"&&c!="36815005"&&c!="36813008"&&c!="36813007")c="";return c}function Fe(){if((i.google_unique_id||0)!=0)return i.google_expandable_exp_id;var a=Lb(["31865000","31865001"],Sb);return i.google_expandable_exp_id=a}
function yf(a){if((a.google_unique_id||0)!=0)return"";a=Lb(["36815005","36815006"],Vb);if(a=="")a=Lb(["36813007","36813008"],Wb);return a}function Je(a){return a.google_expandable_exp_id=="31865001"}Zc.tick("js_parse","js_load");Zc.tick("jl");})()
